---
title: "Richard Trait Annotation"
author: "Oceana Tavasieff"
date: "8/12/2021"
output: html_document
---
The Goal of this Document will be to input a dataset and generate both a trait and an OTU matrix.
  - The ds (dataset) must initially be manually annotated for rhizomorph prescence at DEEMY to the species level.
  -The trait/OTU matrices must have tree names as rownames
  -the trait matrix has traits as column names
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

```{r read in FungalTraits doc}

short_traits <- read_xlsx("~/functional-fungi/FungalTraits 1.2_ver_16Dec_2020.xlsx") %>% rename(Genus = GENUS) 

ecm_short <- short_traits %>% drop_na(Ectomycorrhiza_exploration_type_template) %>% arrange(Genus)
#colnames(short_traits)
```

```{r Install Fun^Fun db which may have more consistent annotations}
# Version: https://zenodo.org/record/1216257

# Via: https://github.com/traitecoevo/fungaltraits

#install.packages("devtools")
#devtools::install_github("ropenscilabs/datastorr")
#devtools::install_github("traitecoevo/fungaltraits")
library(fungaltraits)
```

```{r Access Fun^Fun db, include=FALSE}
#fun_fun_db <-fungal_traits()
long_traits <- fungal_traits() %>% separate(speciesMatched, c("Genus", "Species", "Subspecies", "Etc"), " ")

# Add an exploration type column from the fungaltraits database 
exp_type_1 <- long_traits %>% select(Genus, Species, em_expl)
exp_type_2 <- short_traits %>% select(Genus, Ectomycorrhiza_exploration_type_template)


exp_type <- merge(exp_type_1, exp_type_2) %>% unite(EXP.TYPE, em_expl, Ectomycorrhiza_exploration_type_template, sep = "_", na.rm=T) 

fun_fun_traits <- colnames(fungal_traits())
 
```
#Pull in your dataset

```{r}
richard_raw <- Richard_et_al_OTU_table <- read_delim("Richard et al OTU table.csv", ";", escape_double = FALSE, trim_ws = TRUE)

```

```{r Generate OTU table}
rich_OTU <- richard_raw %>% select(Taxon, EA07:CS09) %>% mutate(Taxon = str_replace(Taxon, " ", "_")) %>% 
  column_to_rownames(var="Taxon") %>% 
  t %>% 
  as.data.frame %>% 
  rownames_to_column(var ="Taxon") %>% mutate(enviro = if_else(str_detect(Taxon, "E"), "arid", "mesic")) %>% relocate(enviro, .after = Taxon) 

rich_rel_OTU <- rich_OTU %>% mutate(sumAbund = select(., c(3:125,)) %>% 
             rowSums(na.rm = TRUE)) %>% 
  relocate(sumAbund, .after = enviro)

for(i in 4:ncol(rich_rel_OTU)) {
  rich_rel_OTU[,i] <- rich_rel_OTU[,i]/rich_rel_OTU$sumAbund
  }
rich_rel_OTU <- rich_rel_OTU %>% 
  mutate(sumAbund = select(., c(4:126,)) %>% 
             rowSums(na.rm = TRUE)) %>% 
  mutate(sumAbund = NULL,
         enviro = NULL)
rich_rel_OTU <- column_to_rownames(rich_rel_OTU, var = "Taxon")

saveRDS(rich_rel_OTU, "NMDS_4_input/richard_OTU_matrix.rds")

```
#Produce trait matrix
```{r}
rich_4tr <- richard_raw %>% select(-"GenBank accession number", -"Closest GenBank species", -"BLAST expected value‡") %>% separate(Taxon, c("Genus", "Species", "Etc"), " ")

richard_annotated <- left_join(rich_4tr, exp_type) %>% rename(Rhizomorph = "Rhizomorph-DEEMY") %>% unite(ID, Genus, Species, sep=" ") %>% 
  mutate(distance =  case_when(grepl("long", "Foraging_distance-DEEMY") ~ "long",
                               grepl("L", EXP.TYPE) ~ "long",grepl("medium", "Foraging_distance-DEEMY")~"medium",
                               grepl("medium", EXP.TYPE) ~ "medium",
                               grepl("M", EXP.TYPE) ~ "medium",
                               grepl("short", "Foraging_distance-DEEMY") ~ "short",
                               grepl("short", EXP.TYPE) ~ "short",
                               grepl("S", EXP.TYPE) ~ "short",
                               grepl("contact", EXP.TYPE) ~ "short",
                               grepl("C", EXP.TYPE)~"short"))%>% unique() #%>% select(-Etc, -"Foraging_distance-DEEMY", -EXP.TYPE, -Rhizomorph, distance) 
richard_annotated$distance <- replace_na(richard_annotated$distance, "unknown")
richard_annotated$Rhizomorph <- replace_na(richard_annotated$Rhizomorph, "unknown")

tr1 <- richard_annotated  %>% select(ID, Rhizomorph:CS09, distance) %>% group_by(distance, Rhizomorph) %>% summarise_at(vars(EA07:CS09), list(sum)) %>% ungroup() %>% 
  mutate(Rhizomorph = ifelse(Rhizomorph == "y", "rhizo", Rhizomorph),
         Rhizomorph = ifelse(Rhizomorph == "n", "norhizo", Rhizomorph)) %>% unite(Trait_species, distance, Rhizomorph, sep = "_" ) %>% mutate(Trait_species = as.character(.$Trait_species)) %>%  column_to_rownames("Trait_species") 

rich_rel_trait <- tr1 %>%   mutate(sumAbund = rowSums(across(where(is.numeric)))) %>%  mutate(across(everything()), . / sumAbund) %>% select(-sumAbund)


saveRDS(rich_rel_trait, "NMDS_4_input/richard_trait_matrix.rds")
```




```{r appendix, eval=FALSE, include=FALSE}
#WE will be producing a matrix that has NA's instead of zeroes. But if we would like to produce a curated matrix with zeroes, this is part of the code that could work:
 #short = if_else(str_detect(distance, "short"), 1, 0),
  #medium = if_else(str_detect(distance, "medium"), 1, 0),
  #long = if_else(str_detect(distance, "long"), 1, 0),
  #rhizo = if_else(str_detect(DEEM_RHIZO, "y"), 1, 0),
  #norhizo = if_else(str_detect(DEEM_RHIZO, "n"), 1, 0),
  #short =~replace(., is.na(.), 0),
  #medium = ~replace(., is.na(.), 0))# %>% 
  #mutate_all(~replace(., is.na(.), 0)

  #short = case_when(grepl("short", distance)~ 1),
         #medium = case_when(grepl("medium", distance)~ 1),
         #long = case_when(grepl("long", distance)~ 1),
         #rhizo = case_when(grepl("y", Rhizomorph)~ 1), 
         #norhizo = case_when(grepl("n", Rhizomorph)~ 1 )
#To make for loop work
trait_matrix <- richard_annotated


for(i in 1:nrow(trait_matrix)){
  if(trait_matrix$distance[i] == "short") {
    trait_matrix$short[i] = trait_matrix$count[i]
  }
  if(trait_matrix$distance[i] == "medium") {
    trait_matrix$medium[i] = trait_matrix$count[i]
  }
  if(trait_matrix$distance[i] == "long") {
    trait_matrix$long[i] = trait_matrix$count[i]
  }
  if(trait_matrix$distance[i] == "unknown") {
    trait_matrix$unknown[i] = trait_matrix$count[i]
  }
  if(trait_matrix$Rhizomorph[i] == "y") {
    trait_matrix$rhizo[i] = trait_matrix$count[i]
  }
  if(trait_matrix$Rhizomorph[i] == "n") {
    trait_matrix$norhizo[i] = trait_matrix$count[i]
  }
  if(trait_matrix$Rhizomorph[i] == "") {
    trait_matrix$unknown[i] = trait_matrix$count[i] + trait_matrix$unknown[i]
  }
}

erl_traits <- trait_matrix %>% select(Plspp, short, medium, long, rhizo, norhizo, unknown)

short<- aggregate(short ~ Plspp, data = erl_traits, sum)
medium <- aggregate(medium ~ Plspp, data = erl_traits, sum)
#long <- aggregate(long ~ Plspp, data = erl_traits, sum)
rhizo <- aggregate(rhizo ~ Plspp, data = erl_traits, sum)
norhizo <- aggregate(norhizo ~ Plspp, data = erl_traits, sum)
unknown <- aggregate(unknown ~ Plspp, data = erl_traits, sum)

etr <-  left_join(unknown, short) %>%
                left_join(., medium) %>%
                left_join(., rhizo) %>%
                left_join(., norhizo) %>% 
  mutate(long = NA) %>% 
  relocate(long, .after = medium) %>%
  column_to_rownames(var = "Plspp")
## Make Mendo TRAIT matrix
mendo_trait_table_foraging <- pygmy.core %>% 
  select(Tree, Trait.ForagingType, Tips) %>% 
  group_by(Tree) %>% 
  arrange(Tree) %>% 
  ungroup() %>% 
  filter(., Trait.ForagingType != "") %>% 
  mutate(row = row_number()) %>%
  pivot_wider(., names_from = Trait.ForagingType, values_from = Tips, values_fill = 0) %>% 
  transmute(Tree = Tree,
            short = shortdistance+contact, 
            medium = mediumdistancefringe+mediumdistancesmooth+mediumdistancemat,
            long = longdistance)

#not 100% sure what row_number does to help pivot.wider--but it works. Thanks stack overflow!

mendo_trait_table_rhizo <- pygmy.core %>% 
  select(Tree, Trait.Rhizomorphs, Tips) %>% 
  group_by(Tree) %>% 
  arrange(Tree) %>% 
  ungroup() %>% 
  filter(., Trait.Rhizomorphs != "") %>% 
    mutate(row = row_number()) %>%
  pivot_wider(., names_from = Trait.Rhizomorphs, values_from = Tips, values_fill = 0) %>% 
  transmute(Tree = Tree,
            norhizo = n,
            rhizo = y)# dropped m column, may have to revisit?


```

```{r eval=FALSE, include=FALSE}
annotated_merge <- left_join(salix, erlandson_annotated, by = "Ecto_spp")%>% mutate(Genus = Genus.x, X = NULL, Genus.x = NULL, Genus.y=NULL, abund = NULL, Subspecies = NULL, Accession_No = NULL, Notes = NULL)  # %>% filter(Species != "sp.") %>%  drop_na(Species) 
# Add an exploration type column from the fungaltraits database 
exp_type_1 <- long_traits %>% select(Genus, Species, em_expl)
exp_type_2 <- short_traits %>% select(Genus, Ectomycorrhiza_exploration_type_template)
exp_type <- merge(exp_type_1, exp_type_2)
# %>% unite(Ecto_ID, Genus:Species, sep = " ", remove = F)


# Check exploration type added correctly
#unique(exp_type$em_expl) # looks good

erlandson_expl <- right_join(annotated_merge, exp_type) %>%  drop_na(Ecto_spp)#

trait_table_erlandson
```