---
title: "V3 Figure Creation and Modification"
author: "Oceana Tavasieff"
output: html_notebook
---

```{r}
library(tidyverse)
library(vegan)
```
#### Ordinate all 4 separately

#### All 4 datasets together

```{r}
samples_raw <- readRDS("V3 Files/sample_dataframe.rds")
OTU_raw <- readRDS("V3 Files/OTU_matrix.rds")
traits_raw <- readRDS("V3 Files/trait_dataframe.rds")
traits_as_taxa_raw <- readRDS("V3 Files/trait_taxa_table.rds")
```

So how do I ordinate outside of phyloseq?
We used a PCoA.

#### Run PERMANOVA w vegan

```{r}
OTU <- as.data.frame(OTU_raw) %>% rownames_to_column("tree")
samples <- samples_raw %>% rownames_to_column("tree") %>% select(tree, enviro, site)

OTU_enviro <- OTU %>% left_join(., samples)

```
```{r}
shannondiv <- diversity(OTU_raw)
head(shannondiv)
````
```{r}
sppdiv_enviro_aov <- aov(shannondiv ~ enviro, data = OTU_enviro)
summary(sppdiv_enviro_aov)

#enviro        1   2.55  2.5538   4.092 0.0457 *
#significant difference in shannon diveristy btw environment?? 
# prob not good if true haha

sppdiv_site_aov <- aov(shannondiv~site, data=OTU_enviro)
summary(sppdiv_site_aov)

#site         3  46.08  15.361   79.75 <2e-16 ***
#   sig  diff in shann div btw sites
#   but both are strongly driven by the lack of spp overlap/beta diversity driven by artificially combining the sites
#   
#   
```
```{r}
sppr<- specnumber(OTU)


# analysis of variance takes the same form as the usual models you'd see in R
# response ~ dependent, data = environmental grouping
sppr_aov <- aov(sppr ~ enviro, data = OTU_enviro)
summary(sppr_aov)

```
```{r}
shandiv_df <- shannondiv %>% 
  # put all those calculations into a data frame
  enframe() %>% 
  # rename columns for ease of joining
  rename(shan_div = value)
```



```{r}

#for permANOVA

OTU_for_perm <- OTU_enviro #%>% mutate(env_code = if_else(enviro == "arid", 1, 2)) %>% select(-enviro, -site)
OTU_perm <- adonis(OTU_raw ~ enviro, data = OTU_for_perm)
OTU_perm
```


#### Trait

```{r}
traits <- as.data.frame(traits_raw) %>% rownames_to_column("tree")

traits_enviro <- traits %>% left_join(., samples)

```

```{r}
shandiv_tr <- diversity(traits_raw)
head(shandiv_tr)
````
```{r}
tr_sppdiv_enviro_aov <- aov(shandiv_tr ~ enviro, data = traits_enviro)
summary(tr_sppdiv_enviro_aov)

#enviro        1   2.55  2.5538   4.092 0.0457 *
#significant difference in shannon diveristy btw environment?? 
# prob not good if true haha

tr_sppdiv_site_aov <- aov(shandiv_tr~site, data=traits_enviro)
summary(tr_sppdiv_site_aov)

#site         3  46.08  15.361   79.75 <2e-16 ***
#   sig  diff in shann div btw sites
#   but both are strongly driven by the lack of spp overlap/beta diversity driven by artificially combining the sites
#   
#   
```
```{r}
tr_perm <- adonis(traits_raw ~ enviro, data = traits_enviro)
tr_perm
```

